# Site settings
title:          a-House
description:    "개발자 원채의 블로그"
url:            "https://ywonchae1.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Wonchae Yang
  url:          https://ywonchae1.github.io
  email:        ywonchae62@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Table Of Contents
toc:
  ordered_list: true

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale